export const tagStyles: Record<string, { color: string; icon: string }> = {
  Boeuf: { color: "bg-red-100 text-red-800", icon: "🥩" },
  Poulet: { color: "bg-yellow-100 text-yellow-800", icon: "🍗" },
  "Fruit de mer": { color: "bg-sky-100 text-sky-800", icon: "🦐" },
  Poisson: { color: "bg-blue-100 text-blue-800", icon: "🐟" },
  Végétarien: { color: "bg-green-100 text-green-800", icon: "🥦" },
  Canard: { color: "bg-amber-100 text-amber-800", icon: "🦆" },
  Entrée: { color: "bg-purple-100 text-purple-800", icon: "🥟" },
  Épicé: { color: "bg-red-200 text-red-900", icon: "🌶️" },
  "Nouilles sautées": { color: "bg-orange-100 text-orange-800", icon: "🍜" },
  "Riz sautés": { color: "bg-amber-100 text-amber-900", icon: "🍚" },
  "Pad thaï": { color: "bg-pink-100 text-pink-800", icon: "🍲" },
  "Plats en sauces": { color: "bg-indigo-100 text-indigo-800", icon: "🍛" },
  Baos: { color: "bg-fuchsia-100 text-fuchsia-800", icon: "🥠" },
  Desserts: { color: "bg-rose-100 text-rose-800", icon: "🍰" },
  Boissons: { color: "bg-cyan-100 text-cyan-800", icon: "🥤" },
};
