# =========================
# APP ID
# =========================
spring.application.name=Minaobackend

# =========================
# SERVER
# =========================
server.port=8080

# =========================
# DATASOURCE : minaodb
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/minaodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=minaouser
spring.datasource.password=17Euskadi06
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE  Dev: create / update   Prod: validate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# =========================
# SECURITY (JWT)
# =========================
# ?? Remplace en prod via variable d'environnement (ex: SECURITY_JWT_SECRET)
security.jwt.secret=change-this-please-32-bytes-minimum-secret-for-hs256!!
# 24h en millisecondes
security.jwt.expiration=86400000

# =========================
# APP CUSTOM PROPERTIES (bindées par AppProperties)
# =========================
# CORS: une seule origine
app.cors.allowed-origins=http://localhost:3000
# (ou en liste)
# app.cors.allowed-origins[0]=http://localhost:3000

# Refresh Token (TTL jours + cookie HttpOnly)
app.auth.refresh-ttl-days=7
app.auth.refresh-cookie-name=rt
app.auth.refresh-cookie-domain=localhost
# Dev: false ; Prod (HTTPS + SameSite=None obligatoire): true
app.auth.refresh-cookie-secure=false

# =========================
# SPRINGDOC / SWAGGER
# =========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

# =========================
# STRIPE (désactivable / placeholder)
# =========================
stripe.secret.key=sk_test_51Rr2s0PK8akuYOXY1oyYkCX2DendDVKZynVC16kauvSfRT0WAwABxjVzfg8M7sQdbw5elw3Rq3jP7x4QfkzNyRVU00eldwhGb7
stripe.public.key=pk_test_51Rr2s0PK8akuYOXY8DnbPNyVMDhwJsbZ0acPCjoC869YHqCIe5hAwtbpxTwiLCZxQlAWVkvzz5tmmEPAmWOS73wn00kstIXb92

# =========================
# LOGGING
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# utile pour voir les drops/creates du schéma :
# logging.level.org.hibernate.tool.schema=DEBUG


