spring.application.name=Minaobackend
# === SERVER ===
server.port=8080

# === DATABASE ===
spring.datasource.url=jdbc:mysql://localhost:3306/minaodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=minaouser
spring.datasource.password=17Euskadi06
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

stripe.secret.key=sk_test_51Rr2s0PK8akuYOXY1oyYkCX2DendDVKZynVC16kauvSfRT0WAwABxjVzfg8M7sQdbw5elw3Rq3jP7x4QfkzNyRVU00eldwhGb7
stripe.public.key=pk_test_51Rr2s0PK8akuYOXY8DnbPNyVMDhwJsbZ0acPCjoC869YHqCIe5hAwtbpxTwiLCZxQlAWVkvzz5tmmEPAmWOS73wn00kstIXb92

logging.level.org.springframework.security=DEBUG
